#!/bin/sh
set -e
stagedFiles=$(git diff --staged --name-only)
echo "Formatterer kode med spotlessApply..."
./gradlew ktfmtFormat
for file in $stagedFiles; do
  if test -f "$file"; then
    git add "$file"
  fi
done
