name: Deploy til prod
on:
  workflow_dispatch:

jobs:
  "deployAppToProd":
    name: "Deploy app to prod"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/prod.yaml"
