name: Deploy til prod
on:
  workflow_dispatch:

jobs:
  "deployAppToProd":
    name: "Deploy app to prod"
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          REF: ${{ github.sha }}
