name: Deploy til dev
on:
  workflow_dispatch:

jobs:
  deployAppToDev:
    name: "Deploy app to dev"
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "CLUSTER": dev-gcp
          "RESOURCE": .nais/dev.yaml
  deployAppToMock:
    name: "Deploy app to mock"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Deploy to mock"
        uses: nais/deploy/actions/deploy@v2
        env:
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/mock.yaml"
