name: "Build and deploy sosialhjelp-kommune-service"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-20.04"
    permissions:
      packages: write
      contents: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/wrapper-validation-action@v3"
      - uses: "actions/setup-java@v4"
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: "compile and run tests"
        run: "./gradlew build buildFatJar"
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v3"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push the Docker image"
        run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/dev.yaml"
  "deployAppToMock":
    name: "Deploy app to mock"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to MOCK"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/mock.yaml"
  "deployAppToProd":
    name: "Deploy app to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/prod.yaml"
