name: "Build and deploy sosialhjelp-kommune-service"
on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: compile and run tests
        run: ./gradlew build buildFatJar
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdigisos
  deployAppToDev:
    name: "Deploy app to dev"
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          REF: ${{ github.sha }}
          VAR: image=${{ needs.build.outputs.image }}
  deployAppToMock:
    name: "Deploy app to mock"
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/mock.yaml
          REF: ${{ github.sha }}
          VAR: image=${{ needs.build.outputs.image }}
  deployAppToProd:
    name: "Deploy app to prod"
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          REF: ${{ github.sha }}
          VAR: image=${{ needs.build.outputs.image }}
